#include "inflate.c"
#include "png.c"
#include "rectpack.c"
#include "image.c"
#include "socket.c"
#include "truetype.c"
#include "stream.c"
#include "riff.c"

#include "approxmath/sincos.c"
#include "approxmath/exp.c"
#include "approxmath/pow.c"
#include "approxmath/asinacos.c"
#include "approxmath/tan.c"

#undef FDLIBM_INTERNAL
#define FDLIBM_INTERNAL static
#include "ieee.c"

#include "fdlibm/e_rem_pio2.c"
#include "fdlibm/k_cos.c"
#include "fdlibm/k_rem_pio2.c"
#include "fdlibm/k_sin.c"
#include "fdlibm/k_standard.c"
#include "fdlibm/k_tan.c"
#include "fdlibm/s_asinh.c"
#include "fdlibm/s_atan.c"
#include "fdlibm/s_cbrt.c"
#include "fdlibm/s_ceil.c"
#include "fdlibm/s_copysign.c"
#include "fdlibm/s_cos.c"
#include "fdlibm/s_erf.c"
#include "fdlibm/s_expm1.c"
#include "fdlibm/s_fabs.c"
#include "fdlibm/s_finite.c"
#include "fdlibm/s_floor.c"
#include "fdlibm/s_frexp.c"
#include "fdlibm/s_ilogb.c"
#include "fdlibm/s_isnan.c"
#include "fdlibm/s_ldexp.c"
#include "fdlibm/s_lib_version.c"
#include "fdlibm/s_log1p.c"
#include "fdlibm/s_logb.c"
#include "fdlibm/s_matherr.c"
#include "fdlibm/s_modf.c"
#include "fdlibm/s_nextafter.c"
#include "fdlibm/s_rint.c"
#include "fdlibm/s_scalbn.c"
#include "fdlibm/s_signgam.c"
#include "fdlibm/s_significand.c"
#include "fdlibm/s_sin.c"
#include "fdlibm/s_tan.c"
#include "fdlibm/s_tanh.c"
#include "fdlibm/w_acos.c"
#include "fdlibm/w_acosh.c"
#include "fdlibm/w_asin.c"
#include "fdlibm/w_atan2.c"
#include "fdlibm/w_atanh.c"
#include "fdlibm/w_cosh.c"
#include "fdlibm/w_exp.c"
#include "fdlibm/w_fmod.c"
#include "fdlibm/w_gamma.c"
#include "fdlibm/w_hypot.c"
#include "fdlibm/w_j0.c"
#include "fdlibm/w_j1.c"
#include "fdlibm/w_jn.c"
#include "fdlibm/w_log.c"
#include "fdlibm/w_log10.c"
#include "fdlibm/w_pow.c"
#include "fdlibm/w_remainder.c"
#include "fdlibm/w_scalb.c"
#include "fdlibm/w_sinh.c"
#include "fdlibm/w_sqrt.c"

#include "vorbis.c"

#include "region.c"
#include "stringset.c"
#include "stream.c"
#include "pairing_heap.c"

#include "codec/codec_impl.h"

#include "test/test.c"
#include "test/pairing_heap.c"
#include "test/treap.c"
